void print_alphabet(void);
int put_char(void);
void print_alphabet_x10(void);
int _islower(int c);
int _abs(int a);
void jack_bauer(void);
void times_table(void);
int add(int a, int b);
void print_to_98(int n);
int _putchar(char c);
int print_last_digit(int a);
int _isalpha(int c);
int print_sign(int n);
void print_times_table(int n);
